- name: Allow jira tcp
  command: firewall-cmd --zone=public --permanent --add-port=8080/tcp
  
- name: Allow jira tcp control
  command: firewall-cmd --zone=public --permanent --add-port=8005/tcp
  
- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: "'con01' not in inventory_hostname_short"
  